from __future__ import annotations

import abc
import typing

class MySQLConnectionAbstract(metaclass=abc.ABCMeta):
    converter: typing.Any = ...
    def __init__(self, **kwargs: typing.Any) -> None: ...
    @property
    def user(self) -> str: ...
    @property
    def server_host(self) -> str: ...
    @property
    def server_port(self) -> int: ...
    @property
    def unix_socket(self) -> str: ...
    @property
    @abc.abstractmethod
    def database(self) -> MySQLConnectionAbstract: ...
    @database.setter
    def database(self, value: typing.Any) -> MySQLConnectionAbstract: ...
    @property
    def can_consume_results(self) -> bool: ...
    def config(self, **kwargs: typing.Any) -> None: ...
    def get_server_version(self) -> tuple[int, ...] | None: ...
    def get_server_info(self) -> str | None: ...
    @property
    @abc.abstractmethod
    def in_transaction(self) -> typing.Any: ...
    def set_client_flags(self, flags: typing.Any) -> list[int]: ...
    def isset_client_flag(self, flag: typing.Any) -> bool: ...
    @property
    def time_zone(self) -> str: ...
    @time_zone.setter
    def time_zone(self, value: typing.Any) -> None: ...
    @property
    def sql_mode(self) -> str: ...
    @sql_mode.setter
    def sql_mode(self, value: typing.Any) -> None: ...
    @abc.abstractmethod
    def info_query(self, query: typing.Any) -> MySQLCursorAbstract: ...
    def set_login(
        self, username: typing.Any | None = ..., password: typing.Any | None = ...
    ) -> None: ...
    def set_unicode(self, value: bool = ...) -> None: ...
    @property
    def autocommit(self) -> bool: ...
    @autocommit.setter
    def autocommit(self, value: typing.Any) -> None: ...
    @property
    def get_warnings(self) -> bool: ...
    @get_warnings.setter
    def get_warnings(self, value: typing.Any) -> None: ...
    @property
    def raise_on_warnings(self) -> bool: ...
    @raise_on_warnings.setter
    def raise_on_warnings(self, value: typing.Any) -> None: ...
    @property
    def unread_result(self) -> bool: ...
    @unread_result.setter
    def unread_result(self, value: bool) -> bool: ...
    @property
    def charset(self) -> str: ...
    @property
    def python_charset(self) -> str: ...
    def set_charset_collation(
        self, charset: typing.Any | None = ..., collation: typing.Any | None = ...
    ) -> None: ...
    @property
    def collation(self) -> str: ...
    @abc.abstractmethod
    def disconnect(self) -> typing.Any: ...
    close: typing.Any = ...
    def connect(self, **kwargs: typing.Any) -> MySQLConnectionAbstract: ...
    def reconnect(self, attempts: int = ..., delay: int = ...) -> None: ...
    @abc.abstractmethod
    def is_connected(self) -> typing.Any: ...
    @abc.abstractmethod
    def ping(
        self, reconnect: bool = ..., attempts: int = ..., delay: int = ...
    ) -> typing.Any: ...
    @abc.abstractmethod
    def commit(self) -> typing.Any: ...
    @abc.abstractmethod
    def cursor(
        self,
        buffered: typing.Any | None = ...,
        raw: typing.Any | None = ...,
        prepared: typing.Any | None = ...,
        cursor_class: typing.Any | None = ...,
        dictionary: typing.Any | None = ...,
        named_tuple: typing.Any | None = ...,
    ) -> MySQLCursorAbstract: ...
    @abc.abstractmethod
    def rollback(self) -> typing.Any: ...
    def start_transaction(
        self,
        consistent_snapshot: bool = ...,
        isolation_level: typing.Any | None = ...,
        readonly: typing.Any | None = ...,
    ) -> None: ...
    def reset_session(
        self,
        user_variables: typing.Any | None = ...,
        session_variables: typing.Any | None = ...,
    ) -> None: ...
    def set_converter_class(self, convclass: typing.Any) -> None: ...
    @abc.abstractmethod
    def get_rows(
        self,
        count: typing.Any | None = ...,
        binary: bool = ...,
        columns: typing.Any | None = ...,
    ) -> typing.Any: ...
    def cmd_init_db(self, database: typing.Any) -> None: ...
    def cmd_query(
        self,
        query: typing.Any,
        raw: bool = ...,
        buffered: bool = ...,
        raw_as_string: bool = ...,
    ) -> None: ...
    def cmd_query_iter(self, statements: typing.Any) -> None: ...
    def cmd_refresh(self, options: typing.Any) -> None: ...
    def cmd_quit(self) -> None: ...
    def cmd_shutdown(self, shutdown_type: typing.Any | None = ...) -> None: ...
    def cmd_statistics(self) -> None: ...
    def cmd_process_info(self) -> None: ...
    def cmd_process_kill(self, mysql_pid: typing.Any) -> None: ...
    def cmd_debug(self) -> None: ...
    def cmd_ping(self) -> None: ...
    def cmd_change_user(
        self,
        username: str = ...,
        password: str = ...,
        database: str = ...,
        charset: int = ...,
    ) -> None: ...
    def cmd_stmt_prepare(self, statement: typing.Any) -> None: ...
    def cmd_stmt_execute(
        self,
        statement_id: typing.Any,
        data: typing.Any = ...,
        parameters: typing.Any = ...,
        flags: int = ...,
    ) -> None: ...
    def cmd_stmt_close(self, statement_id: typing.Any) -> None: ...
    def cmd_stmt_send_long_data(
        self, statement_id: typing.Any, param_id: typing.Any, data: typing.Any
    ) -> None: ...
    def cmd_stmt_reset(self, statement_id: typing.Any) -> None: ...
    def cmd_reset_connection(self) -> None: ...

class MySQLCursorAbstract(metaclass=abc.ABCMeta):
    arraysize: int = ...
    def __init__(self) -> None: ...
    @abc.abstractmethod
    def callproc(self, procname: typing.Any, args: typing.Any = ...) -> typing.Any: ...
    @abc.abstractmethod
    def close(self) -> typing.Any: ...
    @abc.abstractmethod
    def execute(
        self, operation: typing.Any, params: typing.Any = ..., multi: bool = ...
    ) -> typing.Any: ...
    @abc.abstractmethod
    def executemany(self, operation: typing.Any, seqparams: typing.Any) -> typing.Any: ...
    @abc.abstractmethod
    def fetchone(self) -> typing.Any: ...
    @abc.abstractmethod
    def fetchmany(self, size: int = ...) -> typing.Any: ...
    @abc.abstractmethod
    def fetchall(self) -> typing.Any: ...
    def nextset(self) -> None: ...
    def setinputsizes(self, sizes: typing.Any) -> None: ...
    def setoutputsize(
        self, size: typing.Any, column: typing.Any | None = ...
    ) -> None: ...
    def reset(self, free: bool = ...) -> None: ...
    @property
    @abc.abstractmethod
    def description(self) -> typing.Any: ...
    @property
    @abc.abstractmethod
    def rowcount(self) -> typing.Any: ...
    @property
    @abc.abstractmethod
    def lastrowid(self) -> typing.Any: ...
    def fetchwarnings(self) -> list[tuple[str | int, ...]] | None: ...
